# MakeFile function     :: MakeFile for tdx test suite tdx_guest_kernel_img

top_srcdir              ?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
